source 'http://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3'

gem 'jquery-rails'
gem 'omniauth'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'haml'
  gem 'foundation-rails'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-debugger'
  gem 'turn', :require => false
  gem 'thin'
  gem 'better_errors'
  gem 'binding_of_caller'
end
